#ifndef HALCONF_H
#define HALCONF_H
#define HAL_USE_PAL FALSE
#define HAL_USE_SERIAL FALSE
#define HAL_USE_PWM FALSE
#define HAL_USE_ADC FALSE
#define HAL_USE_I2C FALSE
#define HAL_USE_SPI FALSE
#define HAL_USE_CAN FALSE
#define HAL_USE_EXT FALSE
#endif
