CC=arm-none-eabi-gcc
CXX=arm-none-eabi-g++
OBJCOPY=arm-none-eabi-objcopy
CFLAGS=-mcpu=cortex-m4 -mthumb -O2 -ffreestanding -Wall -Isrc
CXXFLAGS=$(CFLAGS) -std=c++17
LDFLAGS=-T src/STM32F407xG.ld -nostdlib

SRC_C=$(wildcard src/rt/*.c) $(wildcard src/hal/*.c) $(wildcard src/ports/*.c) $(wildcard src/startup/*.c)
SRC_CPP=$(wildcard src/*.cpp)
SRC_S=$(wildcard src/startup/*.S) $(wildcard src/ports/*.S)

OBJ=$(patsubst src/%.c,build/%.o,$(SRC_C)) \
    $(patsubst src/%.cpp,build/%.o,$(SRC_CPP)) \
    $(patsubst src/%.S,build/%.o,$(SRC_S))

all: Stage3_test.elf Stage3_test.hex Stage3_test.bin

build/%.o: src/%.c
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) -c $< -o $@

build/%.o: src/%.cpp
	@mkdir -p $(dir $@)
	$(CXX) $(CXXFLAGS) -c $< -o $@

build/%.o: src/%.S
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) -c $< -o $@

Stage3_test.elf: $(OBJ)
	$(CXX) $(OBJ) -o $@ $(LDFLAGS)

Stage3_test.hex: Stage3_test.elf
	$(OBJCOPY) -O ihex $< $@

Stage3_test.bin: Stage3_test.elf
	$(OBJCOPY) -O binary $< $@

clean:
	rm -rf build Stage3_test.elf Stage3_test.hex Stage3_test.bin
