#define CH_CFG_USE_SEMAPHORES             TRUE
#define CH_CFG_USE_MUTEXES                TRUE
#define CH_CFG_USE_MUTEXES_RECURSIVE      TRUE
#define CH_CFG_USE_CONDVARS               TRUE
#define CH_CFG_USE_CONDVARS_TIMEOUT       TRUE
#define CH_CFG_USE_EVENTS                  TRUE
#define CH_CFG_USE_EVENTS_TIMEOUT          TRUE
#define CH_CFG_USE_MESSAGES                TRUE
#define CH_CFG_USE_MESSAGES_PRIORITY       TRUE
#define CH_CFG_USE_DYNAMIC                 TRUE
#define CH_CFG_IDLE_ENTER_HOOK()           ((void)0)
#define CH_CFG_IDLE_LEAVE_HOOK()           ((void)0)
#define CH_CFG_IDLE_LOOP_HOOK()            ((void)0)
#define CH_CFG_SYSTEM_TICK_HOOK()          ((void)0)
#define CH_CFG_SYSTEM_HALT_HOOK()          ((void)0)
#define CH_CFG_TRACE_HOOK()                ((void)0)
#define CH_CFG_RUNTIME_FAULTS_HOOK()      ((void)0)
#define CH_CFG_ST_RESOLUTION               16
#define CH_CFG_ST_FREQUENCY                1000
#define CH_CFG_INTERVALS_SIZE              16
#define CH_CFG_TIME_TYPES_SIZE             16
